# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db4f25e335773ba285b33594d6ee683218f0fcb1f79bc879b685854a6fb24900efead4a342b34c88ceafbebfb9978532ad7ac646a916d7de0136bb74dad506d

test:
  secret_key_base: eaaf4d168a9a1eb414606e08fcc40309f7408eeefb85026677815b04cc89395ab6837ef51df44d687c87b76556ad095c728d9aa02df494bc03dcda74e9c6d889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
